#!/usr/bin/python

from currentflickr import *
from sys import stdout

img = '<img class="ss" src="{0}" alt="{1}" title="{1}" />'.format(currentFlickrURL('Medium 800'), currentFlickrTitle())
stdout.write(img)
